### ISSUE TITLE
What's your favorite language to develop in?

### ISSUE THREAD

**Issue by itzsaga** [dashersw/ama#2]

**Comment by dashersw** [comment]
It's JavaScript, definitely!

It's both expressive, allows you to implement any programming paradigm—whether it's functional or object-oriented—and it just runs everywhere.

As per [Atwood's Law](http://blog.codinghorror.com/the-principle-of-least-power);

> any application that _can_ be written in JavaScript, _will_ eventually be written in JavaScript.
